### ISSUE TITLE
Age at death

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#10]

**Comment by hinri** [comment]
might be replaced with ncit:C156426, which has not exactly the same meaning, but reduces number of ontologies in use

**Comment by gurnoor1990** [comment]
changing to this one from NCIT ontology. resolved to age of death [NCIT:C135383](https://bioportal.bioontology.org/ontologies/NCIT?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C135383)
