### ISSUE TITLE
Small patch to fix the semantic model readme.

### ISSUE THREAD

**Issue by roelj** [fairgenomes/information#107]
First of all, thank you for the great work on creating a national standard!

I have a small patch to fix the SIO term for "female" which currently is the same as the SIO term for "male" in the README.

(Due to the ridiculous way Github treats Git patches I had to ZIP the patch file..)

[0001-Fix-the-link-to-the-female-gender-term.zip](https://github.com/fairgenomes/information/files/4797618/0001-Fix-the-link-to-the-female-gender-term.zip)

You can apply the patch using:
```
git am -S <the-unzipped-file.patch>
```

**Comment by gurnoor1990** [comment]
Thanks @roelj 

Nice, to learn about the git patch, I never used it before. I fixed it manually before, applying the patch.
