### ISSUE TITLE
Phenotypic terms

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#12]

**Comment by joerivandervelde** [comment]
perhaps remove ORDO, dealing with phenotypes here not diseases

**Comment by gurnoor1990** [comment]
For Disease level it is ORDO, for phenotypes it is Orphanet (HPO terms for orde)

**Comment by joerivandervelde** [comment]
Done @ https://github.com/fairgenomes/fairgenomes-semantic-model
