### ISSUE TITLE
Type of phenotypic data

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#14]

**Comment by gurnoor1990** [comment]
Remove some terms from the DC:DCMIType list. For example, "software" is not related to our medical 
datasets

**Comment by gurnoor1990** [comment]
#51 check the overlap

**Comment by joerivandervelde** [comment]
better code listings?

subclass of NCIT 'Document' ?
http://bioportal.bioontology.org/ontologies/NCIT/?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C19498

subclass of CTV3 'Investigations' ?
http://bioportal.bioontology.org/ontologies/RCD/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FRCD%2FX77W7

MeSH 'Diagnostic Techniques and Procedures' ?
http://bioportal.bioontology.org/ontologies/MESH/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FMESH%2FD019937

**Comment by gurnoor1990** [comment]
Rename it to clinical inverstigations performs and add the 

MeSH 'Diagnostic Techniques and Procedures' ?
http://bioportal.bioontology.org/ontologies/MESH/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FMESH%2FD019937

**Comment by joerivandervelde** [comment]
Using DCMI media types. Done for now @ https://github.com/fairgenomes/fairgenomes-semantic-model
