### ISSUE TITLE
Clinical diagnosis

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#15]

**Comment by gurnoor1990** [comment]
JR and JW opinion: Clinical diagnosis and Genetic diagnosis overlap, but it is good to keep them separate. (Good comment to highlight in the manuscript.)

**Comment by gurnoor1990** [comment]
Orpha terms

**Comment by joerivandervelde** [comment]
Make single-select, so it is clear which details/age/variants belong to this particular diagnosis
