### ISSUE TITLE
Molecular diagnosis & Molecular diagnosis other

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#16]

**Comment by hinri** [comment]
is this in conjunction with clinical findings and risk factors or just (any) genetic findings?

**Comment by joerivandervelde** [comment]
Excellent point - you could imagine also reporting known pathogenic variants in healthy individuals due to disease low penetrance. However here does not feel like to right place to do it. So indeed, this field is supposed to be in conjunction with the clinical diagnosis for this patient. Clinical diagnosis may be established without a genetic diagnosis, of course. The description fields must reflect this clearly.

**Comment by joerivandervelde** [comment]
Suggest to split in 'gene' and 'variant' part so we can have a codebook lookup for the genes, as well as parsable variant data (if sticking to a format like 12:4568721C>A)

**Comment by joerivandervelde** [comment]
could be different from Clinical Diagnosis for various reasons, this is not a bad thing

**Comment by joerivandervelde** [comment]
of course, allow for multiple genetic diagnoses

**Comment by gurnoor1990** [comment]
**How to add list of variants, (could it be a text description), cross-reference  ?**

**Comment by gurnoor1990** [comment]
Shall we separate Genetic diagnosis (Genes) and Genetic diagnosis (Variants)?

**Comment by jambelien** [comment]
Good point Gurnoor. If we need the entire list of variants I think cross referencing will be best, most pragmatic right? if it is a certain (small) subset, you might absorb them in the FAIRgenomes ontology?

**Comment by joerivandervelde** [comment]
Suggesting: make this field into Gene-Variant notation only. So:

Clinical Diagnosis -> Select one or multiple (rare) disorders from codebook, often they are already linked to a gene.

Genetic Diagnosis -> Specify causal variant(s) for the above disorders, or perhaps they are new findings. Format HGVS, for example:

AGT:c.803T>C
9:g.22125503G>C
ENST00000003084:c.1431_1433delTTC

**Comment by joerivandervelde** [comment]
use comma-separated HGVS notation of DNA variants causal for disease. Alternatively, you may express other pathogenic molecular mechanisms here.

**Comment by joerivandervelde** [comment]
for clinical genetics: also need classification, esp. for a new variant (VUS, LP, P, ..)

**Comment by gurnoor1990** [comment]
Split it into 2 fields, consult pathologist and genecist

**Comment by gurnoor1990** [comment]
Molecular diagnosis (free text) <- renamed to -> Molecular diagnosis other
