### ISSUE TITLE
Family members affected

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#21]

**Comment by gurnoor1990** [comment]
Option 1: to annotate meta-data 

http://bioportal.bioontology.org/ontologies/APAONTO?p=classes&conceptid=http%3A%2F%2Fontology.apa.org%2Fapaonto%2FtermsonlyOUT%2520(5).owl%23Biological_Family

**Comment by gurnoor1990** [comment]
Subclass of this to annotate data elements
https://bioportal.bioontology.org/ontologies/GSSO/?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C41256

**Comment by joerivandervelde** [comment]
need: pedigree information. in either free text or structured data or image.. ? alternative: add the known inheritance pattern in this family (X-linked, dominant, recessive, etc). Does PassPedigree have a format? use that to provide pedigree info.

**Comment by gurnoor1990** [comment]
Disuss this with Jeroen Baliien, shall we add the pedigree file as a [datatype] here? 

- privacy sensitivity

**Comment by jambelien** [comment]
tricky point. May be better to have a short call and invite a clinical geneticist

**Comment by joerivandervelde** [comment]
Move discussion to https://github.com/fairgenomes/fairgenomes-semantic-model/issues/12
