### ISSUE TITLE
Material type

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#31]

**Comment by gurnoor1990** [comment]
Defination missing

**Comment by joerivandervelde** [comment]
This used to be linkout to CDISC: https://evs.nci.nih.gov/ftp1/CDISC/SDTM/Archive/SDTM%20Terminology%202012-03-23.html

**Comment by gurnoor1990** [comment]
Definition : Type of material collected, e.g. blood, muscle, bone etc

**Comment by gurnoor1990** [comment]
Material types code book still need to be decided

**Comment by joerivandervelde** [comment]
Suggestion, coming from RD3: https://github.com/MIABIS/miabis/wiki/Structured-data-and-lists#material-type

**Comment by joerivandervelde** [comment]
need: "Cell-free DNA", treated differently!

https://bioportal.bioontology.org/ontologies/SNOMEDCT?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSNOMEDCT%2F726740008

**Comment by joerivandervelde** [comment]
list probably not complete, multiple isolates from plasma/urine possible

**Comment by joerivandervelde** [comment]
perhaps use SPREC codes here as well? https://www.liebertpub.com/doi/abs/10.1089/bio.2017.0109

**Comment by gurnoor1990** [comment]
Check with pathologist.

**Comment by joerivandervelde** [comment]
Chosen MIABIS list for time being. See https://github.com/fairgenomes/fairgenomes-semantic-model.
