### ISSUE TITLE
Anatomical source

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#32]

**Comment by joerivandervelde** [comment]
whole UBERON list too big, look for better option, or perhaps use superclasses only?

**Comment by gurnoor1990** [comment]
Discuss this issue with Linekke. 

UBERON Ontology is too big.

**Comment by gurnoor1990** [comment]
snomed anatomical topology.
bodystructure
anatomical structure

**Comment by gurnoor1990** [comment]
Ask a pathologist.

**Comment by joerivandervelde** [comment]
Using cleaned UBERON list at https://github.com/fairgenomes/fairgenomes-semantic-model.
