### ISSUE TITLE
Storage conditions

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#33]

**Comment by hinri** [comment]
what about this one:
https://bioportal.bioontology.org/ontologies/OBI?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0001472

**Comment by gurnoor1990** [comment]
Agreed! OBI terms are freely available

**Comment by joerivandervelde** [comment]
update to include temperature information at the least
also there are more ways of storage in the lab

**Comment by gurnoor1990** [comment]
Contact Biobank teams

**Comment by joerivandervelde** [comment]
Suggestion: use SPREC-codes, see: https://www.liebertpub.com/doi/full/10.1089/bio.2017.0109

**Comment by joerivandervelde** [comment]
Now using 'Long-term storage' from SPREC (https://cdn.ymaws.com/www.isber.org/resource/resmgr/isber_2019/pdf/standard_preanalytical_code_.pdf)
