### ISSUE TITLE
Estimated percentage of tumor cells

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#35]

**Comment by hinri** [comment]
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C127771

**Comment by gurnoor1990** [comment]
http://bioportal.bioontology.org/ontologies/NCIT?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C127771
