### ISSUE TITLE
Amount of input material used

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#36]

**Comment by gurnoor1990** [comment]
Define: Gives background on how much information can be expected to be extracted from the source material

**Comment by gurnoor1990** [comment]
HInrii: 
Purpose: Biosource (Tissue) <-> Extract (DNA/RNA)? <-> Sequence
Extract Information missing

This should be tagged as extract information

**Comment by gurnoor1990** [comment]
May be split technical information to:extract informations i.e. sequencing preparation + technical information i.e. bioinformation

**Comment by gurnoor1990** [comment]
linked to issue #59

**Comment by joerivandervelde** [comment]
Renamed 'Amount of input material used' to 'Amount of input material in ng', and changed value type '[decimals] + [units]' to '[positive integer]'
