### ISSUE TITLE
is a deritative or not?

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#38]

**Comment by gurnoor1990** [comment]
Hinri: If derivative, there should be a link to the primary source. 
With boolean, the primary source should be linked. 



[To check]: Is linking in our data model, be in the scope of the project.

**Comment by joerivandervelde** [comment]
suggest to replace Boolean with Reference to Material instead. If empty, implies this is primary source. if not empty, is derived from this other material.

**Comment by joerivandervelde** [comment]
renamed from ""is a deritative or not"?" to "Derived from" and changed data type from Boolean to 'link to material'
