### ISSUE TITLE
Sample prep kit

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#40]

**Comment by gurnoor1990** [comment]
The sample prep kit could be volatile/ not findable in the long run: information is lost. 

Propose, adhere to the EGA standards. Selection technique used

**Comment by joerivandervelde** [comment]
arguable the best sample prep kit list: https://www.biocompare.com/pfu/13493814/soids/2318393/NGS_Library_Preparation_and_Sample_Prep/NGS_Kits

**Comment by joerivandervelde** [comment]
need:
"Library prep kit" and "Target enrichment kit" (if used)

**Comment by joerivandervelde** [comment]
https://www.ebi.ac.uk/ena/submit/reads-library-strategy relates to "Library prep kit"

**Comment by joerivandervelde** [comment]
rename from "Sample prep kit" to "Library preparation kit"
