### ISSUE TITLE
Sequencing platform

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#41]

**Comment by joerivandervelde** [comment]
hinri: consider long-read platforms & how this impacts the FAIR Genomes model

**Comment by hinri** [comment]
actually there is two:
Sequencing platform (vendor name) GENEPIO:0000071
Sequencing  instrument model (model name) GENEPIO:0001921
(both are required for automated EGA submissions)

**Comment by hinri** [comment]
> hinri: consider long-read platforms & how this impacts the FAIR Genomes model

in particular concerns attributes read-length/insert-size
