### ISSUE TITLE
Type of sequencing

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#42]

**Comment by joerivandervelde** [comment]
hinri: use https://www.ebi.ac.uk/ena/submit/reads-library-strategy

**Comment by gurnoor1990** [comment]
Type of sequencing

**Comment by gurnoor1990** [comment]
add to Decore

**Comment by joerivandervelde** [comment]
Previous suggested, not used but could still be handy elsewhere? https://bioportal.bioontology.org/ontologies/NCIT/?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C18881

**Comment by joerivandervelde** [comment]
added ENA list to codebook
