### ISSUE TITLE
Physical data location

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#49]

**Comment by joerivandervelde** [comment]
Renamed from "Location of data (Physical location)" to "Physical data location"

**Comment by joerivandervelde** [comment]
perhaps we need 'Location Institute' and 'Location Country' ?

**Comment by gurnoor1990** [comment]
Dont use country of birth subclass. Use ISO-standard

**Comment by jambelien** [comment]
one of the ontologies we could use is:
country : http://purl.bioontology.org/ontology/SNOMEDCT/223369002
as synonym it has country (geographical location)
(country is part of Geographical and/or political region of the world which is part of Environment or geographical location)

mappings towards the country from snomed are:
LOINC: http://purl.bioontology.org/ontology/LNC/LP120625-1
NCIT: http://purl.obolibrary.org/obo/NCIT_C25464

or use a property from snomed ct:
geographical location: http://purl.bioontology.org/ontology/SNOMEDCT/758638001
(geographical location is part of measurement property which is part of qualifier value

or use the numeric country code (based on ISO 3166-1 Numeric Country Code)
http://purl.obolibrary.org/obo/NCIT_C54640

**Comment by gurnoor1990** [comment]
USED ISO 3166

**Comment by joerivandervelde** [comment]
better? UN/LOCODE: https://service.unece.org/trade/locode/nl.htm

**Comment by joerivandervelde** [comment]
Moved discussion to https://github.com/fairgenomes/fairgenomes-semantic-model/issues/13
