### ISSUE TITLE
Modelling: Tumor type / event type information missing

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#57]

**Comment by gurnoor1990** [comment]
Diagnosis should be seen as an event, 
Events are linked to samples / new samples.

**Comment by joerivandervelde** [comment]
event could also be, start of a study, then you group individuals

**Comment by joerivandervelde** [comment]
Closing this for now as keeping track of cardinality, events, timestamps, actors, timestamps, other provenance-related metadata etc is outside the scope of defining a semantic meta-data model for sharing NGS data
