### ISSUE TITLE
Missing Information: sequencing provider

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#58]

**Comment by joerivandervelde** [comment]
could this reuse the list of institutes, or do we need more with eg commercial companies?

**Comment by joerivandervelde** [comment]
in addition: we need some kind of 'sequence provider' as part of sample prep, and also as part of bioinformatic analysis. Both could be done by the same or by different parties.

**Comment by gurnoor1990** [comment]
Not sure: This element is important from an Auditors point of view, do we need it for research or analysis purposes?

**Comment by gurnoor1990** [comment]
Also consult Radboud Biobank!

**Comment by gurnoor1990** [comment]
Part of provenance, and not necessary to capture at this stage.
