### ISSUE TITLE
split "Material" and "Technical" into 3

### ISSUE THREAD

**Issue by joerivandervelde** [fairgenomes/information#59]
as discussed with hinri. perhaps it makes sense to split "Material" and "Technical" into 3 parts, following the flow of biosource -> extract -> library -> sequencing -> analysis. for instance:

- Material or BioSource describing the physical sample, location, volumes, etc
- Preparation describing library creation, other wet lab work, prep kits, etc
- Analysis describing any bioinformatic work, software, files, etc

**Comment by joerivandervelde** [comment]
Preparation -> SamplePreparation
Analysis -> BioinformaticAnalysis

**Comment by gurnoor1990** [comment]
**Material information** 

- Sampling time stamp
- Registration time stamp
- Sampling collection protocol
- Deviations from sample protocol
- Reasons for protocol deviation
- Material type
- Anatomical source
- Storage conditions
- Expiration date
- Estimated percentage of tumor cells
- Location of sample (Physical location)
- "is a deritative or not"?

 

**Sample preparation information**

- Amount of input material used
- Sample prep kit
- PCR-free yes/no
- Enrichment panel used
- UMIs present yes/no
- Targeted insert size
- Intended read length


**Technical information**  

- Sequencing date
- Sequencing platform
- Sequencing datatypes
- Sequencing average read depth
- Observed read length
- Observed insert size
- Location of data (Physical location)
- Location of data (abstract location) / Data owner etc\.
- Data formats stored
- Algorithms used
- Bioinformatic protocols used
- Special parameters used
- Follows international WGS guidelines
-
