### ISSUE TITLE
Primary affiliated institute

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#60]

**Comment by joerivandervelde** [comment]
how to define: is this the center that added the data ?

**Comment by gurnoor1990** [comment]
center that added the data, could be default value:

**Comment by gurnoor1990** [comment]
We let the biobank stay in the list and we add all the hospitals.

**Comment by gurnoor1990** [comment]
For the moment this is Dutch

Use AGB codes

**Comment by jambelien** [comment]
for an explanation on how AGB-codes ares used see (in Dutch): https://www.knmp.nl/praktijkvoering/bekostiging/vastleggen-gegevens-voorschrijvers

**Comment by jambelien** [comment]
example of AGB-webzoeker: https://www.agbcode.nl/Webzoeker/Details/1060693
point is these are only Dutch codes

**Comment by jambelien** [comment]
I found an international hospital identifier code. But unfortunately its licensed: https://www.hibcc.org/hinapi/

**Comment by jambelien** [comment]
At https://zibs.nl/wiki/Zorgaanbieder-v3.3(2019NL)#13138  the national health base data set using ZIBs refers to UZI and VektisAGB. So I will contact Nictiz to ask: 1) if we can use (freely) this codelist and how to obtain/access it 2) ask if there exists a international hospital identifier list

**Comment by jambelien** [comment]
Mailed Nictiz.

**Comment by joerivandervelde** [comment]
302 hospitals @ https://www.zorgkaartnederland.nl/ziekenhuis
