### ISSUE TITLE
FAIRGenomes Codebook: SNOMEDCT, ICD10,HP limited terms

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#66]
All ontology terms limited to 7984

**Comment by gurnoor1990** [comment]
CPT terms for procedural history as well

**Comment by gurnoor1990** [comment]
Pending for now, Will be fixed in the next version of the codebook. 
I will upload the full list to the google sheets and tsv files.

Codebook 3.0

**Comment by joerivandervelde** [comment]
Codebook size limitations are solved in https://github.com/fairgenomes/fairgenomes-semantic-model
