### ISSUE TITLE
Missing information: Research Study details

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#68]

**Comment by joerivandervelde** [comment]
Indeed, we need a 'Study' to group patients, samples, etc. This has come up multiple times, e.g. in discussions with WP4 or harmonizing with RD3 (https://github.com/molgenis/RD3_database).

**Comment by joerivandervelde** [comment]
Some inspiration:
RD3 study: https://github.com/molgenis/RD3_database/blob/master/datamodel/study.md
ISA-TAB study: https://isa-specs.readthedocs.io/en/latest/isatab.html#study-section
MIABIS study: https://github.com/MIABIS/miabis/wiki/Data-describing-Study

**Comment by joerivandervelde** [comment]
Has been added
