### ISSUE TITLE
Quality information missing in sequence information

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#76]

**Comment by gurnoor1990** [comment]
Commented in #47 as well

**Comment by joerivandervelde** [comment]
Feedback Lennart, consider:
- "Percentage Q30" (percentage of bases called with a phred-scale quality of 30 or higher, meaning the error chance is less than 1:1000)
- "Percentage TR20" (percentage of the target sequence on which 20 or more unique reads were successfully mapped)
- Average insert size (NOTE: already present as "Observed insert size")

**Comment by joerivandervelde** [comment]
These have been added now
