### ISSUE TITLE
Organisation creating the consent

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#98]

**Comment by gurnoor1990** [comment]
Please check this element with regards to the semantic model for IC. In the semantic model we are capturing Name of the organisation, Id of the organisation and type of the organisation. 

Do you think, we should capture all 3, or just the organisation ID is enough.

**Comment by gurnoor1990** [comment]
Shall we use BBMRI code to capture organisation ID?

**Comment by esthervanenckevort** [comment]
BBMRI might not have all organisations, but would be a good first default. Having a name is important to keep it human readable so I would really prefer to have it. Any node should have a class associated with it, so the class should be there as well. It can be a different class is the organisation is not a biobank.

**Comment by gurnoor1990** [comment]
Right! 

So we should have three elements then, 

- Organization Name, 
- Organization ID,
- Organization Class

**Comment by gurnoor1990** [comment]
Organization Name -> Free text 
Organization ID -> ID/URL
Organization Class -> Subclass of OBI:0000245 or IOBC [(example)](http://bioportal.bioontology.org/ontologies/IOBC?p=classes&conceptid=http%3A%2F%2Fpurl.jp%2Fbio%2F4%2Fid%2F201006013045719032
) or MIABIS. 

Note: MIABIS biobank is not a subset of the organisation

**Comment by gurnoor1990** [comment]
http://purl.jp/bio/4/subject/Location_cat

**Comment by joerivandervelde** [comment]
can we reuse list of institutes for 'data available in other institutes' ?

**Comment by joerivandervelde** [comment]
Done @ https://github.com/fairgenomes/fairgenomes-semantic-model
