### ISSUE TITLE
version

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#99]

**Comment by gurnoor1990** [comment]
This element is similar to #95  . Although that is the information printed on the leaflet. Do we need both?

**Comment by esthervanenckevort** [comment]
Yes, both the consent form and the leaflet have their own version and these can differ

**Comment by gurnoor1990** [comment]
Alright, thanks! will keep them both then.

**Comment by gurnoor1990** [comment]
@esthervanenckevort  
Shall we rename them to

- Leaflet version
- Gc model version

**Comment by esthervanenckevort** [comment]
I would suggest the following:
- Information Leaflet version
- Consent form version
